config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to => "tweets#index"
  resources :users
  resources :tweets do
    resources :replies
  end
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
  validates :body, :presence => true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :replies
  validates :body, :presence => true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :replies
  after_create :send_welcome_message


  def send_welcome_message
    UserMailer.signup_confirmation(self).deliver
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit :username, :email, :password, :password_confirmation
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :edit]
  respond_to :html, :js

  def index
    @tweets = Tweet.all.order("created_at DESC").page(params[:page])
    @search = params[:query]
     if @search == nil
       render ('tweets/index.html.erb')
     else
       @search_results = Tweet.basic_search(@search)
       render :index
     end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      respond_to do |format|
        format.html { redirect_to  tweets_path }
        format.js { flash.now[:notice] = "Tweet successfully added!" }
      end
    else
      format.js { flash.now[:alert] = "Tweet body cannot be blank!" }
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to  tweets_path }
      format.js { flash.now[:notice] = "Tweet successfully deleted!" }
    end
  end

  # def search
  #   @tweets = Tweet.search do
  #     keywords params[:tweet_id]
  #   end.results
  #
  #   respond_to do |format|
  #     format.html { render :action => "tweets" }
  #     format.xml { render :xml => @tweets }
  #   end
  # end

private
  def tweet_params
    params.require(:tweet).permit(:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Itweet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
  <% else %>
  <li><%= link_to "Join us", new_user_registration_path %></li>
  <li><%= link_to "Login", new_user_session_path %></li>
<% end %>
</ul>
</nav>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>


</body>
</html>

app/views/tweets/_form.html.erb
<%= render "layouts/errors", :object => @tweet %>

<%= form_for @tweet, remote: true do |f| %>
<%= f.label :body %>
<%= f.text_field :body %>
<%= f.submit %>
<% end %>

app/views/tweets/_search.html.erb
<form action="/tweets?query" method="get">
  <label for="search">Search:
    <input id="search" name="query" type="text" placeholder="Search:">
  </label>
  <button class="tiny">Search</button>
</form>

app/views/tweets/_tweet.html.erb
<tr class="tweet" id="<%= tweet.id %>">
  <td><%= tweet.body %></td>
  <td><%= tweet.user.username %></td>
  <td><%= tweet.created_at.strftime("%B %d, %Y") %></td>
  <td><%= link_to 'Show', tweet %></td>
  <td><%= link_to 'Destroy', tweet, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/tweets/create.js.erb
<% if @tweet.save %>
  $('#new_tweet').remove();
  $('#new_tweet_link').show();
  $('#tweets tbody').prepend('<%= j render(@tweet) %>');
  $(".notice").html("<%= flash[:notice] %>");
<% else %>
  $(".alert").html("<%= flash[:alert] %>");
<% end %>

app/views/tweets/destroy.js.erb
$("#<%= @tweet.id %>").remove();
$(".notice").html("<%= flash[:notice] %>");

app/views/tweets/index.html.erb
<h1>Tweets</h1>






<div class="row">
  <div class="large-6 columns">
    <%= render ('search') %>
  </div>
</div>



<% if @search_results != [] && @search_results != nil %>
<div class="row">
  <div class="large-12 columns">
    <h2>Search Results:</h2>

    <ul>
      <% @search_results.each do |result| %>
      <li><a href="/tweets/<%= result.id %>"><%= result.body %></a></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>



<p><%= link_to "New Tweet", new_tweet_path, id: "new_tweet_link", remote: true %></p>
<div class="container">
  <table id="tweets">
    <thead>
      <tr>
        <th>Body</th>
        <th>Username</th>
        <th>Timestamp</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody class="page">
      <%= render @tweets %>
      <%= paginate @tweets %>
    </tbody>
  </table>
</div>

app/views/tweets/index.js.erb
$("#tweets").append("<tbody class='page'><%= escape_javascript(render(@tweets)) %></tbody>");

app/views/tweets/new.html.erb
<%= render 'form' %>

app/views/tweets/new.js.erb
$('#new_tweet_link').hide().after('<%= j render("form") %>');

app/views/tweets/show.html.erb
<h1><%= @tweet.body %></h1>

<h3><%= @tweet.created_at %> by <%= @tweet.user.username %></h3>

<% if current_user == @tweet.user %>
<p><%= link_to "Delete", tweet_path(@tweet),
:data => {:confirm => "You sure?",
  :method => "delete"} %></p>
  <% end %>
  <p><%= link_to "Return to all tweets", tweets_path %></p>